name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.2.4"

    - uses: leafo/gh-actions-luarocks@v4

    - name: build
      run: |
        luarocks install busted

    - name: test day 01
      run: |
        cd lua/01/
        lua test.lua

    - name: test day 02
      run: |
        cd lua/02/
        lua test.lua